### PR TITLE
Add nonEditable name prop

### LINKED ISSUE #19: Cannot make task name in the task list non editable
Hi,

I was trying to use this component but in my use case, I cannot allow the user to edit the task name by clicking it. I looked at the code and saw that this is not currently possible. 

@guiqui is this repository still maintained? I would gladly open a PR to make this configuration possible, but I haven't seen much activity lately here.

### PR DESCRIPTION
**Pull request by ericreis**
This prop is used to control whether the TaskRow inside TaskList is editable or not.
Fixes #19.

### CODE REVIEW

**Comment by ericreis** [comment]
@guiqui There were some conflicts due to linting. Even though there was an eslintrc file in the repository.

**Comment by guiqui** [comment]
Thank you Eric!

**Comment by ericreis** [comment]
You're welcome @guiqui. I will probably work on some other improvements here whenever possible. I'll try to make some PRs here.

**Comment by adback03** [comment]
I noticed this never got released. Can someone push these changes to NPM? As it stands right now, there is no way to make the list list non-editable.

**Comment by qron** [comment]
I have tried to use this patch installing the package directly from github url.
Unfortunately for me, passing the nonEditableName props does not work: the TaskList component seems to never have the nonEditable props from his parent.

Need to look further in debug mode, maybe I have missed something.

Anyway, I have figured out a workaround for now: simply setting pointerEvents: 'none' in config props (taskList.task.style).

**Comment by ohitsdoh** [comment]
FYI docs probably need updating, setting nonEditableName seems to work for me

**Comment by ohitsdoh** [comment]
FYI docs probably need updating, setting nonEditableName seems to work for me.

**Pull request merged**
